require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MetadataController do

  # This should return the minimal set of attributes required to create a valid
  # Metadatum. As you add validations to Metadatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "phone" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MetadataController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all metadata as @metadata" do
      metadatum = Metadatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:metadata).should eq([metadatum])
    end
  end

  describe "GET show" do
    it "assigns the requested metadatum as @metadatum" do
      metadatum = Metadatum.create! valid_attributes
      get :show, {:id => metadatum.to_param}, valid_session
      assigns(:metadatum).should eq(metadatum)
    end
  end

  describe "GET new" do
    it "assigns a new metadatum as @metadatum" do
      get :new, {}, valid_session
      assigns(:metadatum).should be_a_new(Metadatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested metadatum as @metadatum" do
      metadatum = Metadatum.create! valid_attributes
      get :edit, {:id => metadatum.to_param}, valid_session
      assigns(:metadatum).should eq(metadatum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Metadatum" do
        expect {
          post :create, {:metadatum => valid_attributes}, valid_session
        }.to change(Metadatum, :count).by(1)
      end

      it "assigns a newly created metadatum as @metadatum" do
        post :create, {:metadatum => valid_attributes}, valid_session
        assigns(:metadatum).should be_a(Metadatum)
        assigns(:metadatum).should be_persisted
      end

      it "redirects to the created metadatum" do
        post :create, {:metadatum => valid_attributes}, valid_session
        response.should redirect_to(Metadatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metadatum as @metadatum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metadatum.any_instance.stub(:save).and_return(false)
        post :create, {:metadatum => { "phone" => "invalid value" }}, valid_session
        assigns(:metadatum).should be_a_new(Metadatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metadatum.any_instance.stub(:save).and_return(false)
        post :create, {:metadatum => { "phone" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metadatum" do
        metadatum = Metadatum.create! valid_attributes
        # Assuming there are no other metadata in the database, this
        # specifies that the Metadatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Metadatum.any_instance.should_receive(:update_attributes).with({ "phone" => "MyString" })
        put :update, {:id => metadatum.to_param, :metadatum => { "phone" => "MyString" }}, valid_session
      end

      it "assigns the requested metadatum as @metadatum" do
        metadatum = Metadatum.create! valid_attributes
        put :update, {:id => metadatum.to_param, :metadatum => valid_attributes}, valid_session
        assigns(:metadatum).should eq(metadatum)
      end

      it "redirects to the metadatum" do
        metadatum = Metadatum.create! valid_attributes
        put :update, {:id => metadatum.to_param, :metadatum => valid_attributes}, valid_session
        response.should redirect_to(metadatum)
      end
    end

    describe "with invalid params" do
      it "assigns the metadatum as @metadatum" do
        metadatum = Metadatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metadatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => metadatum.to_param, :metadatum => { "phone" => "invalid value" }}, valid_session
        assigns(:metadatum).should eq(metadatum)
      end

      it "re-renders the 'edit' template" do
        metadatum = Metadatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metadatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => metadatum.to_param, :metadatum => { "phone" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metadatum" do
      metadatum = Metadatum.create! valid_attributes
      expect {
        delete :destroy, {:id => metadatum.to_param}, valid_session
      }.to change(Metadatum, :count).by(-1)
    end

    it "redirects to the metadata list" do
      metadatum = Metadatum.create! valid_attributes
      delete :destroy, {:id => metadatum.to_param}, valid_session
      response.should redirect_to(metadata_url)
    end
  end

end
